# coding: utf-8

"""
    C4C REST API

    Access to the Crowd4Cash Crowdlending Platform through an API

    The version of the OpenAPI document: 2.0.0
    Contact: info@crowd4cash.ch
    Created by: https://crowd4cash.ch
"""

from crowd_4_cash_python_sdk.paths.intermediary_loan.put import SetDefinitiveHandoverDate
from crowd_4_cash_python_sdk.paths.loan.post import SubmitLoanApplication
from crowd_4_cash_python_sdk.paths.intermediary_loan.post import SubmitPartnerLoanApplication
from crowd_4_cash_python_sdk.paths.rental_loan.post import SubmitRentalLoanApplication
from crowd_4_cash_python_sdk.apis.tags.application_api_raw import ApplicationApiRaw


class ApplicationApi(
    SetDefinitiveHandoverDate,
    SubmitLoanApplication,
    SubmitPartnerLoanApplication,
    SubmitRentalLoanApplication,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ApplicationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ApplicationApiRaw(api_client)
