# coding: utf-8

"""
    C4C REST API

    Access to the Crowd4Cash Crowdlending Platform through an API

    The version of the OpenAPI document: 2.0.0
    Contact: info@crowd4cash.ch
    Created by: https://crowd4cash.ch
"""

from crowd_4_cash_python_sdk.paths.contracts.get import GetAllRaw
from crowd_4_cash_python_sdk.paths.contracts_rental_loan_loan_id.get import GetLoanContractRaw
from crowd_4_cash_python_sdk.paths.contracts_loan_id.get import GetSpecificRaw
from crowd_4_cash_python_sdk.paths.contracts_partner_id_loan_id.get import GetSpecificIntermediaryLoanContractRaw


class ContractsApiRaw(
    GetAllRaw,
    GetLoanContractRaw,
    GetSpecificRaw,
    GetSpecificIntermediaryLoanContractRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
