# coding: utf-8

"""
    C4C REST API

    Access to the Crowd4Cash Crowdlending Platform through an API

    The version of the OpenAPI document: 2.0.0
    Contact: info@crowd4cash.ch
    Created by: https://crowd4cash.ch
"""

from crowd_4_cash_python_sdk.paths.custom_portfolio.get import GetCustomizedPortfolioRaw
from crowd_4_cash_python_sdk.paths.portfolio.get import GetInvestmentsRaw


class PortfolioApiRaw(
    GetCustomizedPortfolioRaw,
    GetInvestmentsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
