# coding: utf-8

"""
    C4C REST API

    Access to the Crowd4Cash Crowdlending Platform through an API

    The version of the OpenAPI document: 2.0.0
    Contact: info@crowd4cash.ch
    Created by: https://crowd4cash.ch
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from crowd_4_cash_python_sdk import schemas  # noqa: F401


class BiddingSubmitBidsRequest(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['ConnectorBid']:
            return ConnectorBid

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['ConnectorBid'], typing.List['ConnectorBid']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'BiddingSubmitBidsRequest':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'ConnectorBid':
        return super().__getitem__(i)

from crowd_4_cash_python_sdk.model.connector_bid import ConnectorBid
