# coding: utf-8

"""
    C4C REST API

    Access to the Crowd4Cash Crowdlending Platform through an API

    The version of the OpenAPI document: 2.0.0
    Contact: info@crowd4cash.ch
    Created by: https://crowd4cash.ch
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from crowd_4_cash_python_sdk import schemas  # noqa: F401


class ConnectedInvestor(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    An investor whose investments are made indirectly through connector
    """


    class MetaOapg:
        
        class properties:
            investorId = schemas.Int32Schema
            
            
            class investorType(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'investorType':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class investorName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'investorName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            pendingInvestmentsCount = schemas.Int32Schema
            pendingInvestmentsTotal = schemas.Float64Schema
            activeInvestmentsCount = schemas.Int32Schema
            activeInvestmentsTotal = schemas.Float64Schema
            __annotations__ = {
                "investorId": investorId,
                "investorType": investorType,
                "investorName": investorName,
                "pendingInvestmentsCount": pendingInvestmentsCount,
                "pendingInvestmentsTotal": pendingInvestmentsTotal,
                "activeInvestmentsCount": activeInvestmentsCount,
                "activeInvestmentsTotal": activeInvestmentsTotal,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["investorId"]) -> MetaOapg.properties.investorId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["investorType"]) -> MetaOapg.properties.investorType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["investorName"]) -> MetaOapg.properties.investorName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pendingInvestmentsCount"]) -> MetaOapg.properties.pendingInvestmentsCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pendingInvestmentsTotal"]) -> MetaOapg.properties.pendingInvestmentsTotal: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["activeInvestmentsCount"]) -> MetaOapg.properties.activeInvestmentsCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["activeInvestmentsTotal"]) -> MetaOapg.properties.activeInvestmentsTotal: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["investorId", "investorType", "investorName", "pendingInvestmentsCount", "pendingInvestmentsTotal", "activeInvestmentsCount", "activeInvestmentsTotal", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["investorId"]) -> typing.Union[MetaOapg.properties.investorId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["investorType"]) -> typing.Union[MetaOapg.properties.investorType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["investorName"]) -> typing.Union[MetaOapg.properties.investorName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pendingInvestmentsCount"]) -> typing.Union[MetaOapg.properties.pendingInvestmentsCount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pendingInvestmentsTotal"]) -> typing.Union[MetaOapg.properties.pendingInvestmentsTotal, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["activeInvestmentsCount"]) -> typing.Union[MetaOapg.properties.activeInvestmentsCount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["activeInvestmentsTotal"]) -> typing.Union[MetaOapg.properties.activeInvestmentsTotal, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["investorId", "investorType", "investorName", "pendingInvestmentsCount", "pendingInvestmentsTotal", "activeInvestmentsCount", "activeInvestmentsTotal", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        investorId: typing.Union[MetaOapg.properties.investorId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        investorType: typing.Union[MetaOapg.properties.investorType, None, str, schemas.Unset] = schemas.unset,
        investorName: typing.Union[MetaOapg.properties.investorName, None, str, schemas.Unset] = schemas.unset,
        pendingInvestmentsCount: typing.Union[MetaOapg.properties.pendingInvestmentsCount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        pendingInvestmentsTotal: typing.Union[MetaOapg.properties.pendingInvestmentsTotal, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        activeInvestmentsCount: typing.Union[MetaOapg.properties.activeInvestmentsCount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        activeInvestmentsTotal: typing.Union[MetaOapg.properties.activeInvestmentsTotal, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ConnectedInvestor':
        return super().__new__(
            cls,
            *args,
            investorId=investorId,
            investorType=investorType,
            investorName=investorName,
            pendingInvestmentsCount=pendingInvestmentsCount,
            pendingInvestmentsTotal=pendingInvestmentsTotal,
            activeInvestmentsCount=activeInvestmentsCount,
            activeInvestmentsTotal=activeInvestmentsTotal,
            _configuration=_configuration,
            **kwargs,
        )
