# coding: utf-8

"""
    C4C REST API

    Access to the Crowd4Cash Crowdlending Platform through an API

    The version of the OpenAPI document: 2.0.0
    Contact: info@crowd4cash.ch
    Created by: https://crowd4cash.ch
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from crowd_4_cash_python_sdk import schemas  # noqa: F401


class ManualOptionRule(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class loanRating(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'loanRating':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            totalAmountForInvestment = schemas.Float64Schema
            minimumInterestRate = schemas.Float64Schema
            minimumPerBid = schemas.Float64Schema
            maximumPerBid = schemas.Float64Schema
            reinvest = schemas.BoolSchema
            secondaryMarket = schemas.BoolSchema
            durationFrom = schemas.Int32Schema
            durationTo = schemas.Int32Schema
            isEnabled = schemas.BoolSchema
            
            
            class currency(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'currency':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "loanRating": loanRating,
                "totalAmountForInvestment": totalAmountForInvestment,
                "minimumInterestRate": minimumInterestRate,
                "minimumPerBid": minimumPerBid,
                "maximumPerBid": maximumPerBid,
                "reinvest": reinvest,
                "secondaryMarket": secondaryMarket,
                "durationFrom": durationFrom,
                "durationTo": durationTo,
                "isEnabled": isEnabled,
                "currency": currency,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["loanRating"]) -> MetaOapg.properties.loanRating: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalAmountForInvestment"]) -> MetaOapg.properties.totalAmountForInvestment: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["minimumInterestRate"]) -> MetaOapg.properties.minimumInterestRate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["minimumPerBid"]) -> MetaOapg.properties.minimumPerBid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["maximumPerBid"]) -> MetaOapg.properties.maximumPerBid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reinvest"]) -> MetaOapg.properties.reinvest: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secondaryMarket"]) -> MetaOapg.properties.secondaryMarket: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["durationFrom"]) -> MetaOapg.properties.durationFrom: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["durationTo"]) -> MetaOapg.properties.durationTo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isEnabled"]) -> MetaOapg.properties.isEnabled: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["loanRating", "totalAmountForInvestment", "minimumInterestRate", "minimumPerBid", "maximumPerBid", "reinvest", "secondaryMarket", "durationFrom", "durationTo", "isEnabled", "currency", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["loanRating"]) -> typing.Union[MetaOapg.properties.loanRating, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalAmountForInvestment"]) -> typing.Union[MetaOapg.properties.totalAmountForInvestment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["minimumInterestRate"]) -> typing.Union[MetaOapg.properties.minimumInterestRate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["minimumPerBid"]) -> typing.Union[MetaOapg.properties.minimumPerBid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["maximumPerBid"]) -> typing.Union[MetaOapg.properties.maximumPerBid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reinvest"]) -> typing.Union[MetaOapg.properties.reinvest, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secondaryMarket"]) -> typing.Union[MetaOapg.properties.secondaryMarket, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["durationFrom"]) -> typing.Union[MetaOapg.properties.durationFrom, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["durationTo"]) -> typing.Union[MetaOapg.properties.durationTo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isEnabled"]) -> typing.Union[MetaOapg.properties.isEnabled, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> typing.Union[MetaOapg.properties.currency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["loanRating", "totalAmountForInvestment", "minimumInterestRate", "minimumPerBid", "maximumPerBid", "reinvest", "secondaryMarket", "durationFrom", "durationTo", "isEnabled", "currency", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        loanRating: typing.Union[MetaOapg.properties.loanRating, None, str, schemas.Unset] = schemas.unset,
        totalAmountForInvestment: typing.Union[MetaOapg.properties.totalAmountForInvestment, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        minimumInterestRate: typing.Union[MetaOapg.properties.minimumInterestRate, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        minimumPerBid: typing.Union[MetaOapg.properties.minimumPerBid, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        maximumPerBid: typing.Union[MetaOapg.properties.maximumPerBid, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        reinvest: typing.Union[MetaOapg.properties.reinvest, bool, schemas.Unset] = schemas.unset,
        secondaryMarket: typing.Union[MetaOapg.properties.secondaryMarket, bool, schemas.Unset] = schemas.unset,
        durationFrom: typing.Union[MetaOapg.properties.durationFrom, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        durationTo: typing.Union[MetaOapg.properties.durationTo, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        isEnabled: typing.Union[MetaOapg.properties.isEnabled, bool, schemas.Unset] = schemas.unset,
        currency: typing.Union[MetaOapg.properties.currency, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ManualOptionRule':
        return super().__new__(
            cls,
            *args,
            loanRating=loanRating,
            totalAmountForInvestment=totalAmountForInvestment,
            minimumInterestRate=minimumInterestRate,
            minimumPerBid=minimumPerBid,
            maximumPerBid=maximumPerBid,
            reinvest=reinvest,
            secondaryMarket=secondaryMarket,
            durationFrom=durationFrom,
            durationTo=durationTo,
            isEnabled=isEnabled,
            currency=currency,
            _configuration=_configuration,
            **kwargs,
        )
