# coding: utf-8

"""
    C4C REST API

    Access to the Crowd4Cash Crowdlending Platform through an API

    The version of the OpenAPI document: 2.0.0
    Contact: info@crowd4cash.ch
    Created by: https://crowd4cash.ch
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from crowd_4_cash_python_sdk import schemas  # noqa: F401


class Status(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Loan status
    """


    class MetaOapg:
        enum_value_to_name = {
            "All": "ALL",
            "Funded": "FUNDED",
            "Active": "ACTIVE",
            "Closed": "CLOSED",
            "Defaulted": "DEFAULTED",
        }
    
    @schemas.classproperty
    def ALL(cls):
        return cls("All")
    
    @schemas.classproperty
    def FUNDED(cls):
        return cls("Funded")
    
    @schemas.classproperty
    def ACTIVE(cls):
        return cls("Active")
    
    @schemas.classproperty
    def CLOSED(cls):
        return cls("Closed")
    
    @schemas.classproperty
    def DEFAULTED(cls):
        return cls("Defaulted")
